# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_ast_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoAstWindow(object):
    def setupUi(self, InfoAstWindow):
        InfoAstWindow.setObjectName("InfoAstWindow")
        InfoAstWindow.resize(500, 450)
        InfoAstWindow.setMinimumSize(QtCore.QSize(500, 450))
        InfoAstWindow.setMaximumSize(QtCore.QSize(500, 450))
        self.verticalLayoutWidget = QtWidgets.QWidget(InfoAstWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(37, 0, 421, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.combo_box_info_ast = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.combo_box_info_ast.setObjectName("combo_box_info_ast")
        self.verticalLayout.addWidget(self.combo_box_info_ast)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pb_start_info_ast = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_ast.setMinimumSize(QtCore.QSize(0, 50))
        self.pb_start_info_ast.setObjectName("pb_start_info_ast")
        self.verticalLayout.addWidget(self.pb_start_info_ast)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(InfoAstWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoAstWindow)

    def retranslateUi(self, InfoAstWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoAstWindow.setWindowTitle(_translate("InfoAstWindow", "Окно астрономии"))
        self.label.setText(_translate("InfoAstWindow", "<html><head/><body><p>Выбрать нужный график</p></body></html>"))
        self.pb_start_info_ast.setText(_translate("InfoAstWindow", "Нарисовать график"))
