# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InfoWindow(object):
    def setupUi(self, InfoWindow):
        InfoWindow.setObjectName("InfoWindow")
        InfoWindow.resize(400, 550)
        InfoWindow.setMinimumSize(QtCore.QSize(400, 550))
        InfoWindow.setMaximumSize(QtCore.QSize(400, 550))
        self.verticalLayoutWidget = QtWidgets.QWidget(InfoWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 0, 342, 536))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.verticalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_start_info_solar_system = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_solar_system.setMinimumSize(QtCore.QSize(160, 0))
        self.pb_start_info_solar_system.setObjectName("pb_start_info_solar_system")
        self.horizontalLayout.addWidget(self.pb_start_info_solar_system)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_start_info_solar_evolution = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_solar_evolution.setMinimumSize(QtCore.QSize(160, 0))
        self.pb_start_info_solar_evolution.setObjectName("pb_start_info_solar_evolution")
        self.horizontalLayout.addWidget(self.pb_start_info_solar_evolution)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_start_info_earth_moon_sun = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_earth_moon_sun.setMinimumSize(QtCore.QSize(160, 0))
        self.pb_start_info_earth_moon_sun.setObjectName("pb_start_info_earth_moon_sun")
        self.horizontalLayout_2.addWidget(self.pb_start_info_earth_moon_sun)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pb_start_info_change_g = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_change_g.setMinimumSize(QtCore.QSize(160, 0))
        self.pb_start_info_change_g.setObjectName("pb_start_info_change_g")
        self.horizontalLayout_2.addWidget(self.pb_start_info_change_g)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pb_start_info_info_ast = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_info_ast.setMinimumSize(QtCore.QSize(160, 0))
        self.pb_start_info_info_ast.setObjectName("pb_start_info_info_ast")
        self.horizontalLayout_3.addWidget(self.pb_start_info_info_ast)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.pb_start_info_info = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start_info_info.setMinimumSize(QtCore.QSize(160, 60))
        self.pb_start_info_info.setObjectName("pb_start_info_info")
        self.horizontalLayout_3.addWidget(self.pb_start_info_info)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(InfoWindow)
        QtCore.QMetaObject.connectSlotsByName(InfoWindow)

    def retranslateUi(self, InfoWindow):
        _translate = QtCore.QCoreApplication.translate
        InfoWindow.setWindowTitle(_translate("InfoWindow", "Окно справочных сведений "))
        self.pb_start_info_solar_system.setText(_translate("InfoWindow", "Справочные сведения \n"
"о режиме\n"
"\"Модель Солнечной\n"
"системы\""))
        self.pb_start_info_solar_evolution.setText(_translate("InfoWindow", "Справочные сведения \n"
"о режиме \n"
"\"Модель эволюции\n"
"Солнца\""))
        self.pb_start_info_earth_moon_sun.setText(_translate("InfoWindow", "Справочные сведения\n"
"о режиме \n"
"\"Модель Земля\n"
"Луна Солнце\""))
        self.pb_start_info_change_g.setText(_translate("InfoWindow", "Справочные сведения \n"
"о режиме \n"
"\"Моделирование изменения\n"
"закона всемирного тяготения\""))
        self.pb_start_info_info_ast.setText(_translate("InfoWindow", "Справочные сведения\n"
"о режиме \n"
"\"Справочные сведения\n"
"по астрономии\""))
        self.pb_start_info_info.setText(_translate("InfoWindow", "О программе "))
