# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(150, 30, 500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.pb_solar_system = QtWidgets.QPushButton(self.centralwidget)
        self.pb_solar_system.setGeometry(QtCore.QRect(10, 30, 125, 75))
        self.pb_solar_system.setObjectName("pb_solar_system")
        self.pb_earth_moon_sun = QtWidgets.QPushButton(self.centralwidget)
        self.pb_earth_moon_sun.setGeometry(QtCore.QRect(10, 220, 125, 75))
        self.pb_earth_moon_sun.setObjectName("pb_earth_moon_sun")
        self.pb_info_ast = QtWidgets.QPushButton(self.centralwidget)
        self.pb_info_ast.setGeometry(QtCore.QRect(10, 450, 125, 75))
        self.pb_info_ast.setObjectName("pb_info_ast")
        self.pb_solar_evolution = QtWidgets.QPushButton(self.centralwidget)
        self.pb_solar_evolution.setGeometry(QtCore.QRect(660, 30, 125, 75))
        self.pb_solar_evolution.setObjectName("pb_solar_evolution")
        self.pb_change_g = QtWidgets.QPushButton(self.centralwidget)
        self.pb_change_g.setGeometry(QtCore.QRect(660, 220, 125, 75))
        self.pb_change_g.setObjectName("pb_change_g")
        self.pb_info = QtWidgets.QPushButton(self.centralwidget)
        self.pb_info.setGeometry(QtCore.QRect(660, 450, 125, 75))
        self.pb_info.setObjectName("pb_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное окно "))
        self.pb_solar_system.setText(_translate("MainWindow", "Модель \n"
"Солнечной \n"
"системы"))
        self.pb_earth_moon_sun.setText(_translate("MainWindow", "Модель Земля\n"
"Луна и Солнце"))
        self.pb_info_ast.setText(_translate("MainWindow", "Справочные сведения \n"
"по астрономии"))
        self.pb_solar_evolution.setText(_translate("MainWindow", "Модель\n"
"эволюции \n"
"Солнца"))
        self.pb_change_g.setText(_translate("MainWindow", "Моделирование \n"
"изменения закона \n"
"всемирного тяготения "))
        self.pb_info.setText(_translate("MainWindow", "Справочные сведения\n"
"о программе"))
